const fs = require('node:fs/promises')

async function createIconsExportFile(iconsSource, targetFile, relativePathToIconsFolderFromTargetFile) {
    try {
        let icons = await fs.readdir(iconsSource)
        /* RESET EXISTING FILE CONTENT */
        fs.writeFile(targetFile, '\r\n' + '/* THIS FILE IS AUTOMATICALLY GENERATED FROM SVG ICONS IN THE ASSETS FOLDER. */' + '\r\n' + '\r\n')

        console.log(icons);
        let iconsLinks = []
        let iconsNames = []

        for (let i = 0; i < icons.length; i++) {

            if (icons[i].endsWith('.svg')) {
                let iconName = icons[i].split('.')[0].split(' ').join('').split('-').join('')
                let iconLink = relativePathToIconsFolderFromTargetFile + icons[i]

                iconsLinks.push(`"${iconLink}"`)
                iconsNames.push(`"${iconName}"`)

                fs.appendFile(targetFile,
                    'import ' + iconName + ' from "' + iconLink + '";' + '\r\n'
                )

            }

            if (i === icons.length - 1) {
                fs.appendFile(targetFile,
                    '\r\n' +
                    '\r\n' +
                    'export {' + '\r\n' +
                    ''
                )

                for (let j = 0; j < icons.length; j++) {
                    if (icons[j].endsWith('.svg')) {
                        let iconName = icons[j].split('.')[0].split(' ').join('').split('-').join('')
                        fs.appendFile(targetFile,
                            '    ' + iconName + ',' + '\r\n'
                        )
                    }
                }

                fs.appendFile(targetFile,
                    '}'
                )

                /* Aslo write the icons preview file */
                fs.writeFile('../src/static/icons/iconsPreview.js', '\r\n' + '/* THIS FILE IS AUTOMATICALLY GENERATED FROM SVG ICONS IN THE ASSETS FOLDER. */' + '\r\n' + '\r\n')

                fs.appendFile('../src/static/icons/iconsPreview.js',
                    
                    'let Cont = document.querySelector(".Cont")' + '\r\n' + '\r\n' +
    
                    'let iconsLinks = [' + iconsLinks + ']' + '\r\n' +
                    'let iconsNames = [' + iconsNames + ']' + '\r\n' + '\r\n' +

                    'for (let i = 0; i < iconsLinks.length; i++){' + '\r\n' +
                    '    Cont.innerHTML +='+ '\r\n' +
                    '       `' + '\r\n' +
                    '       <section class="Icon">' + '\r\n' +
                    '           <img src="${iconsLinks[i]}">' + '\r\n' +
                    '           <h5 class="Name">${iconsNames[i]}</h5>' + '\r\n' +
                    '       </section>' + '\r\n' +
                    '       `' + '\r\n' +
                    '}'
                )
            }
        }

    } catch (error) {
        console.error('there was an error:', error.message);
    }
}

createIconsExportFile('../src/images/', '../src/static/icons/index.js', '../../images/')
